name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Publicar site
        run: echo "Publicando site..."

      - name: Upload para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v2
