name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  verify:
    name: Verify index.html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for index.html
        run: |
          if [ ! -f index.html ]; then
            echo "Erro: arquivo index.html não encontrado no diretório raiz"
            exit 1
          fi

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Upload artifact (root files)
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
